# -*- coding: utf-8 -*-

#
# Licensed Materials - Property of esse.io
#
# (C) Copyright esse.io. 2015 All Rights Reserved
#
# Author: frank (frank@esse.io)
#
#


'''
    api request constant
'''

# ACTIONS

# 0) ACTION RESOURCE
RESOURCE_SESSION = 'session'
RESOURCE_ACTIVITY = 'activity'
RESOURCE_CHILD = 'child'
RESOURCE_MEMBER = 'child'
RESOURCE_FAMILY = 'family'
RESOURCE_DATADICT = 'datadict'
RESOURCE_BRANCH = 'branch'
RESOURCE_ORGANIZATION = 'organization'
RESOURCE_ADDRCODE = 'addrcode'
RESOURCE_ADMIN = 'admin'
RESOURCE_NEWS = 'news'
RESOURCE_CAROUSEL = 'carousel'
RESOURCE_BUG = 'bug'

# 1) FAMILY ACTION
ACTION_FAMILY_CREATE = 'ACTION_FAMILY_CREATE'
ACTION_FAMILY_UPDATE = 'ACTION_FAMILY_UPDATE'
ACTION_FAMILY_DELETE = 'ACTION_FAMILY_DELETE'
ACTION_FAMILY_LIST = 'ACTION_FAMILY_LIST'
ACTION_FAMILY_DETAIL = 'ACTION_FAMILY_DETAIL'
ACTION_FAMILY_RESET_PASSWD = 'ACTION_FAMILY_RESET_PASSWD'
ACTION_FAMILY_CHILD_LIST = 'ACTION_FAMILY_CHILD_LIST'
ACTION_FAMILY_MEMBER_LIST = 'ACTION_FAMILY_MEMBER_LIST'
ACTION_FAMILY_ATTEND_ACTIVITY_LIST = 'ACTION_FAMILY_ATTEND_ACTIVITY_LIST'


RESOURCE_FAMILY_STATUS_INACTIVE = 'INACTIVE'
RESOURCE_FAMILY_STATUS_ACTIVE = 'ACTIVE'

# 2) SESSION ACTION
ACTION_SESSION_CREATE = 'ACTION_SESSION_CREATE'
ACTION_SESSION_DELETE = 'ACTION_SESSION_DELETE'
ACTION_SESSION_RENEW = 'ACTION_SESSION_RENEW'

# 3) ACTIVITY ACTION
ACTION_ACTIVITY_CREATE = 'ACTION_ACTIVITY_CREATE'
ACTION_ACTIVITY_UPDATE = 'ACTION_ACTIVITY_UPDATE'
ACTION_ACTIVITY_DELETE = 'ACTION_ACTIVITY_DELETE'
ACTION_ACTIVITY_LIST = 'ACTION_ACTIVITY_LIST'
ACTION_ACTIVITY_DETAIL = 'ACTION_ACTIVITY_DETAIL'

# 4) CHILD_ACTION
ACTION_CHILD_LIST = 'ACTION_CHILD_LIST'
ACTION_CHILD_CREATE = 'ACTION_CHILD_CREATE'
ACTION_CHILD_UPDATE = 'ACTION_CHILD_UPDATE'
ACTION_CHILD_DELETE = 'ACTION_CHILD_DELETE'
ACTION_CHILD_DETAIL = 'ACTION_CHILD_DETAIL'


# 4) MEMBER_ACTION
ACTION_MEMBER_LIST = 'ACTION_MEMBER_LIST'
ACTION_MEMBER_CREATE = 'ACTION_MEMBER_CREATE'
ACTION_MEMBER_UPDATE = 'ACTION_MEMBER_UPDATE'
ACTION_MEMBER_DELETE = 'ACTION_MEMBER_DELETE'
ACTION_MEMBER_DETAIL = 'ACTION_MEMBER_DETAIL'


# 6) DATADICT ACTION
ACTION_DATADICT_CREATE = 'ACTION_DATADICT_CREATE'
ACTION_DATADICT_UPDATE = 'ACTION_DATADICT_UPDATE'
ACTION_DATADICT_DELETE = 'ACTION_DATADICT_DELETE'
ACTION_DATADICT_LIST = 'ACTION_DATADICT_LIST'
ACTION_DATADICT_DETAIL = 'ACTION_DATADICT_DETAIL'

# 7) BRANCH ACTION
ACTION_BRANCH_CREATE = 'ACTION_BRANCH_CREATE'
ACTION_BRANCH_UPDATE = 'ACTION_BRANCH_UPDATE'
ACTION_BRANCH_DELETE = 'ACTION_BRANCH_DELETE'
ACTION_BRANCH_LIST = 'ACTION_BRANCH_LIST'
ACTION_BRANCH_DETAIL = 'ACTION_BRANCH_DETAIL'

# 8) ORGANIZATION ACTION
ACTION_ORGANIZATION_CREATE = 'ACTION_ORGANIZATION_CREATE'
ACTION_ORGANIZATION_UPDATE = 'ACTION_ORGANIZATION_UPDATE'
ACTION_ORGANIZATION_DELETE = 'ACTION_ORGANIZATION_DELETE'
ACTION_ORGANIZATION_LIST = 'ACTION_ORGANIZATION_LIST'
ACTION_ORGANIZATION_DETAIL = 'ACTION_ORGANIZATION_DETAIL'
ACTION_ORGANIZATION_ADMIN_LIST = 'ACTION_ORGANIZATION_ADMIN_LIST'
ACTION_ORGANIZATION_ADMIN_SEARCH = 'ACTION_ORGANIZATION_ADMIN_SEARCH'
ACTION_ORGANIZATION_ADMIN_ADD = 'ACTION_ORGANIZATION_ADMIN_ADD'
ACTION_ORGANIZATION_ADMIN_DELETE = 'ACTION_ORGANIZATION_ADMIN_DELETE'
ACTION_ORGANIZATION_ACTIVITY_LIST = 'ACTION_ORGANIZATION_ACTIVITY_LIST'

# 9) ATTACHMENT
ATTACHMENT_MAX_SIZE = 5242880   # max attachment size 5M
ATTACHMENT_VALID_IMG_TYPE = ['jpeg', 'png']

# 10) ADDRCODE ACTION
ACTION_ADDRCODE_CREATE = 'ACTION_ADDRCODE_CREATE'
ACTION_ADDRCODE_UPDATE = 'ACTION_ADDRCODE_UPDATE'
ACTION_ADDRCODE_DELETE = 'ACTION_ADDRCODE_DELETE'
ACTION_ADDRCODE_LIST = 'ACTION_ADDRCODE_LIST'
ACTION_ADDRCODE_DETAIL = 'ACTION_ADDRCODE_DETAIL'

# 11) ADMIN ACTION
ACTION_ADMIN_CREATE = 'ACTION_ADMIN_CREATE'
ACTION_ADMIN_UPDATE = 'ACTION_ADMIN_UPDATE'
ACTION_ADMIN_DELETE = 'ACTION_ADMIN_DELETE'
ACTION_ADMIN_LIST = 'ACTION_ADMIN_LIST'
ACTION_ADMIN_DETAIL = 'ACTION_ADMIN_DETAIL'
ACTION_ADMIN_RESET_PASSWD = 'ACTION_ADMIN_RESET_PASSWD'
ACTION_ADMIN_ORGANIZATION_LIST = 'ACTION_ADMIN_ORGANIZATION_LIST'
ACTION_ADMIN_BRANCH_LIST = 'ACTION_ADMIN_BRANCH_LIST'

RESOURCE_ADMIN_STATUS_INACTIVE = 'INACTIVE'
RESOURCE_ADMIN_STATUS_ACTIVE = 'ACTIVE'


# 12) NEWS ACTION
ACTION_NEWS_CREATE = 'ACTION_NEWS_CREATE'
ACTION_NEWS_UPDATE = 'ACTION_NEWS_UPDATE'
ACTION_NEWS_DELETE = 'ACTION_NEWS_DELETE'
ACTION_NEWS_LIST = 'ACTION_NEWS_LIST'
ACTION_NEWS_DETAIL = 'ACTION_NEWS_DETAIL'


# 13) CAROUSEL ACTION
ACTION_CAROUSEL_CREATE = 'ACTION_CAROUSEL_CREATE'
ACTION_CAROUSEL_DELETE = 'ACTION_CAROUSEL_DELETE'
ACTION_CAROUSEL_LIST = 'ACTION_CAROUSEL_LIST'


# 14) review status
REVIEW_STATUS_PENDING = 'pending'
REVIEW_STATUS_APPROVED = 'approved'
REVIEW_STATUS_REJECTED = 'rejected'

# 15) request type
APIREQ_SESSION = 'session'
APIREQ_ZENWEB = 'zenweb'

# 15) Language constants
LANG_SUPPORTED = ['en', 'zh_cn']
LANG_DFT = 'zh_cn'
LANG_EN = 'en'
LANG_ZH_CN = 'zh_cn'


# 16) BUG ACTION
ACTION_BUG_CREATE = 'ACTION_BUG_CREATE'
ACTION_BUG_UPDATE = 'ACTION_BUG_UPDATE'
ACTION_BUG_DELETE = 'ACTION_BUG_DELETE'
ACTION_BUG_LIST = 'ACTION_BUG_LIST'
ACTION_BUG_DETAIL = 'ACTION_BUG_DETAIL'


# 17) BUG status
BUG_STATUS_NEW = 'new'
BUG_STATUS_WORKING = 'working'
BUG_STATUS_RESOLVED = 'resolved'
BUG_STATUS_VERIFIED = 'verified'
