# -*- coding: utf-8 -*-

#
# Licensed Materials - Property of esse.io
#
# (C) Copyright esse.io. 2015 All Rights Reserved
#
# Author: frank (frank@esse.io)
#
#


'''
    This files records allthe error code for api
'''


INVALID_PARAMETERS_PROVIDED = 'INVALID_PARAMETERS_PROVIDED'
USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE'

SESSION_CREATION_FAILURE = 'SESSION_CREATION_FAILURE'
SESSION_DELETE_FAILURE = 'SESSION_CREATION_FAILURE'

ACTIVITY_REGISTRATION_FAILURE = 'ACTIVITY_REGISTRATION_FAILURE'

CHILD_CREATION_FAILURE = 'CHILD_CREATION_FAILURE'
CHILD_DELETE_FAILURE = 'CHILD_CREATION_FAILURE'

FAMILY_CREATION_FAILURE = 'CHILD_CREATION_FAILURE'
FAMILY_DELETE_FAILURE = 'CHILD_CREATION_FAILURE'

UNKNOWN_SERVER_FAILUER = 'UNKNOWN_SERVER_FAILUER'
