# commen error code
INVALID_PARAMETERS_PROVIDED = 1000

# user action error code
USER_REGISTRATION_FAILURE = 1200

# session action error code
SESSION_CREATION_FAILURE = 1300
SESSION_DELETE_FAILURE = 1301

# activity action error code
ACTIVITY_REGISTRATION_FAILURE = 1400

# child action error code
CHILD_CREATION_FAILURE = 1500
CHILD_DELETE_FAILURE = 1501

# family action error code
FAMILY_CREATION_FAILURE = 1600
FAMILY_DELETE_FAILURE = 1601


# unknow server FAILURE
UNKNOWN_SERVER_FAILUER = 2000
